version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: karaoke-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: karaoke

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: karaoke-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      MONGO_URI: mongodb://mongodb:27017
      DATABASE_NAME: karaoke
    depends_on:
      - mongodb

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: karaoke-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongodb_data:
